# netlify.toml

[build]
  # এই লাইনটি Netlify-কে বলে যে npm install কমান্ডটি চালাতে হবে।
  command = "npm install" 
  functions = "netlify/functions"
  
[functions]
  node_bundler = "esbuild"
  node_version = "18"
